# Generated by Django 4.1.5 on 2023-01-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-craeted_on']},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
