# Generated by Django 4.1.5 on 2023-01-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0002_alter_item_options_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='craeted_on',
            new_name='created_on',
        ),
    ]
