# Generated by Django 4.1.5 on 2023-01-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitapp', '0003_alter_item_options_rename_craeted_on_item_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
